.PHONY: clean All

All:
	@echo "----------Building project:[ Match4Logic - Debug ]----------"
	@cd "Match4Logic" && "$(MAKE)" -f  "Match4Logic.mk"
clean:
	@echo "----------Cleaning project:[ Match4Logic - Debug ]----------"
	@cd "Match4Logic" && "$(MAKE)" -f  "Match4Logic.mk" clean
